name: Build AWS EKS structure

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

  

